name: nigiri
services:

  # RPC daemon
  bitcoin:
    image: getumbrel/bitcoind:v28.0
    container_name: bitcoin
    user: "${UID:-1000}:${GID:-1000}"
    restart: on-failure
    stop_grace_period: 30s
    ports:
      - 18443:18443
      - 18444:18444
      # ZMQ
      - 28332:28332
      - 28333:28333
    volumes:
      - ./volumes/bitcoin:/data/.bitcoin
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=admin1", "-rpcpassword=123", "getblockchaininfo"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquid:
    image: ghcr.io/vulpemventures/elements:latest
    container_name: liquid
    user: "${UID:-1000}:${GID:-1000}"
    command:
      - -datadir=config
    ports:
      - 18884:18884
      - 18886:18886
      # ZMQ
      - 38332:38332
      - 38333:38333
    volumes:
      - ./volumes/elements/:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "elements-cli", "-regtest", "-rpcuser=admin1", "-rpcpassword=123", "getblockchaininfo"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Block explorer server
  electrs:
    image: ghcr.io/vulpemventures/electrs:latest
    container_name: electrs
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --network
      - regtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - bitcoin:18443
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30000
      - --electrum-rpc-addr
      - 0.0.0.0:50000
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      bitcoin:
        condition: service_healthy
    ports:
      - 50000:50000
      - 30000:30000
    volumes:
      - ./volumes/bitcoin/:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30000/blocks/tip/hash"]
      interval: 5s
      timeout: 5s
      retries: 5

  electrs-liquid:
    image: ghcr.io/vulpemventures/electrs-liquid:latest
    container_name: electrs-liquid
    entrypoint:
      - /build/electrs
    command:
      - -vvvv
      - --parent-network
      - regtest
      - --network
      - liquidregtest
      - --daemon-dir
      - /config
      - --daemon-rpc-addr
      - liquid:18884
      - --cookie
      - admin1:123
      - --http-addr
      - 0.0.0.0:30001
      - --electrum-rpc-addr
      - 0.0.0.0:50001
      - --cors
      - "*"
      - --jsonrpc-import
    depends_on:
      liquid:
        condition: service_healthy
    ports:
      - 50001:50001
      - 30001:30001
    volumes:
      - ./volumes/elements/:/config
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:30001/blocks/tip/hash"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Block explorer frontend
  esplora:
    image: ghcr.io/vulpemventures/esplora:latest
    container_name: esplora
    depends_on:
      electrs:
        condition: service_healthy
    environment:
      API_URL: http://localhost:3000
    ports:
      - 5000:5000
    restart: unless-stopped

  esplora-liquid:
    image: ghcr.io/vulpemventures/esplora:latest
    container_name: esplora-liquid
    depends_on:
      electrs-liquid:
        condition: service_healthy
    environment:
      API_URL: http://localhost:3001
    ports:
      - 5001:5000
    restart: unless-stopped

  # LN services
  lnd:
    container_name: lnd
    image: lightninglabs/lnd:v0.18.4-beta.rc2
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      bitcoin:
        condition: service_healthy
    volumes:
      - ./volumes/lnd:/data/.lnd
    environment:
      HOME: /data
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "9735:9735" # p2p
      - "10009:10009" # grpc"
      - "18080:18080" # rest"
  
  tap:
    container_name: tap
    image: lightninglabs/taproot-assets:v0.4.1
    user: "${UID:-1000}:${GID:-1000}"
    depends_on:
      bitcoin:
        condition: service_healthy
      lnd:
        condition: service_healthy
    volumes:
      - ./volumes/tapd:/data/.tapd
      - ./volumes/lnd:/data/.lnd
    environment:
      HOME: /data
    command:
      - --network=regtest
      - --debuglevel=debug 
      - --lnd.host=lnd:10009 
      - --lnd.macaroonpath=/data/.lnd/data/chain/bitcoin/regtest/admin.macaroon 
      - --lnd.tlspath=/data/.lnd/tls.cert
    restart: unless-stopped
    stop_grace_period: 5m30s
    ports:
      - "10029:10029" # grpc
      - "8089:8089" # rest"

  cln:
    container_name: cln
    image: elementsproject/lightningd:latest
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      EXPOSE_TCP: "true"
      LIGHTNINGD_NETWORK: regtest
      LIGHTNINGD_DATA: .lightning
    command:
      - --lightning-dir=.lightning
      - --alias=nigiri
      - --bind-addr=0.0.0.0:9935
      - --bitcoin-rpcconnect=bitcoin:18443
      - --bitcoin-rpcpassword=123 
      - --bitcoin-rpcuser=admin1
      - --log-level=debug
      - --network=regtest
      - --grpc-port=9836
    depends_on:
      bitcoin:
        condition: service_healthy
    ports:
      - 9935:9935 # p2p
      - 9835:9835 # rpc
      - 9836:9836 # grpc
    restart: unless-stopped
    volumes:
      - ./volumes/lightningd:/.lightning
      - ./volumes/bitcoin:/etc/bitcoin

networks:
  default:
    name: nigiri
